feat:[PLG-2739]: Implement CREATE flow for GitOps Application
harness/harness-cli pull request #44
Opened 2023-09-08 03:17 UTC by neelam-harness

2023-09-11 22:22 UTC, neelam-harness reviewed
LGTM

2023-09-12 16:14 UTC, neelam-harness commented on utils.go
> +	fmt.Printf("urltest", urlWithQueryParams)
let's remove this.

2023-09-12 16:14 UTC, neelam-harness commented on opcluster.yml
> +gitops:
do we need this for application ?

2023-09-12 16:26 UTC, Debanitrkl commented
Added a new sub-command that takes in the YAML to create GitOps Cluster resource on Harness platform.

Sample YAML:

```
gitops:
  name: gitops-application
  projectIdentifier: default_project
  orgIdentifier: default
  type: application
  application:
    metadata:
      namespace: default
      clusterName: gitopscluster
      labels:
        harness.io/serviceRef: gitopsservice
        harness.io/envRef: gitopsenv
    spec:
      source:
        repoURL: https://github.com/harness-community/harnesscd-example-apps
        path: guestbook
        targetRevision: master
      destination:
        server: https://kubernetes.default.svc
        namespace: default
  agentIdentifier: AGENT_NAME
  clusterIdentifier: gitopscluster
  repoIdentifier: gitopsrepo
 ```
 Here, `AGENT_NAME` is a constant and asks for input from the user.
 
 Command:
 ```
 harness gitops-application --file applications.yml apply
 ```
 
 Asks for AGENT_NAME input from the user:
 
 ```
 Trying to create or update gitops-application using the yaml= applications.yml
? Enter a valid AgentIdentifier: debacligitops
```
Following output:
```
Creating GitOps-Application with id:  gitops-application-2
Data:  {
 "application": {
  "metadata": {
   "name": "gitops-application",
   "namespace": "default",
   "clusterName": "gitopscluster",
   "labels": {
    "harness.io/envRef": "gitopsenv",
    "harness.io/serviceRef": "gitopsservice"
   },
   "Annotations": null
  },
  "spec": {
   "source": {
    "repoURL": "https://github.com/harness-community/harnesscd-example-apps",
    "path": "guestbook",
    "targetRevision": "master"
   },
   "destination": {
    "server": "https://kubernetes.default.svc",
    "namespace": "default"
   }
  }
 }
}
Data:  {}
Successfully created GitOps-Application with id= gitops-application
```

2023-09-12 16:38 UTC, neelam-harness commented on client.go
> +	fmt.Println("requestBody")
Please remove these.

2023-09-12 16:38 UTC, neelam-harness commented on constants.go
> +const GITOPS_APPLICATION_ENDPOINT = "applications"
Please add it in an alphabetical order.

2023-09-12 16:38 UTC, neelam-harness commented on gitops-application.go
> +	// entityURL := strings.TrimSuffix(baseURL, "/agents/")
Please remove this.

2023-09-12 16:38 UTC, neelam-harness commented on client.go
> +	printJson(requestBody)
Please remove this

2023-09-12 16:38 UTC, neelam-harness commented on gitops-application.go
> +
Nit: remove empty line.

2023-09-12 16:38 UTC, neelam-harness commented on gitops-application.go
> +			//fmt.Sprintf("%s/%s/spec", GITOPS_APPLICATION_ENDPOINT, applicationName), map[string]string{
Please remove the commented code.

2023-09-12 19:33 UTC, neelam-harness commented on client.go
> +	_ "fmt"
do we need this ?

2023-09-12 19:33 UTC, neelam-harness commented on gitops-application.go
> +		printJson(applicationPayload)
We need to remove this.

2023-09-12 19:33 UTC, neelam-harness commented on gitops-cluster.go
> +import (
This file is already checked in, please make sure this doesn't override the existing file. Seems like a rebase issue.

2023-09-12 19:33 UTC, neelam-harness commented on types.go
> +type UpdateMask struct {
I don't think `UpdateMask` is required anymore, since it's being declared internally in line# 285.

2023-09-12 19:33 UTC, neelam-harness commented on utils.go
> -
Let's not make any changes in the file that is not being touched by the current use-case.

2023-09-13 04:21 UTC, Ompragash requested changes
Reordered constants to preserve the chronological sequence.

2023-09-13 04:21 UTC, Ompragash commented on constants.go
>  const GITOPS_AGENT_IDENTIFIER_PLACEHOLDER = "AGENT_NAME"
```suggestion
const GITOPS_AGENT_IDENTIFIER_PLACEHOLDER = "AGENT_NAME"
const GITOPS_APPLICATION_ENDPOINT = "applications"
```

2023-09-13 04:35 UTC, Ompragash approved these changes
Tested the changes by creating GitOps resources on Harness and LGTM!
Thanks @Debanitrkl!

2023-09-13 05:05 UTC, merged